project:
  type: website

website:
  title: "Madison travel time estimates"
  navbar:
    left:
      - href: analysis.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true